config/routes.rb
Rails.application.routes.draw do

  # root
  root 'pages#home'

  # wordgates
  get 'get_started', to: 'pages#get_started', as: 'get_started'
  get 'get_page', to: 'pages#get_page', as: 'get_page'
  get 'get_your_page', to: 'pages#get_your_page', as: 'get_your_page'
  get 'done', to: 'pages#thank_you', as: 'thank_you'
  resources :writers

  get 'how_it_works', to: 'pages#how_it_works', as: 'how_it_works'
  get 'features', to: 'pages#features', as: 'features'
  get 'about_us', to: 'pages#about_us', as: 'about_us'
  get 'our_pricing', to: 'pages#our_pricing', as: 'our_pricing'


  # course
  get 'course', to: 'course#lesson_two', as: 'lesson_intro'
  get 'lesson_one', to: 'course#lesson_one', as: 'lesson_one'
  get 'lesson_two', to: 'course#lesson_two', as: 'lesson_two'
  get 'lesson_three', to: 'course#lesson_three', as: 'lesson_three'
  get 'lesson_four', to: 'course#lesson_four', as: 'lesson_four'
  get 'lesson_five', to: 'course#lesson_five', as: 'lesson_five'
  get 'lesson_six', to: 'course#lesson_six', as: 'lesson_six'
  get 'lesson_seven', to: 'course#lesson_seven', as: 'lesson_seven'
  get 'lesson_eight', to: 'course#lesson_eight', as: 'lesson_eight'

  post 'student_question', to: 'course#student_question', as: 'student_question'
  get 'message_sent', to: 'course#message_sent', as: 'message_sent'


  post 'get_started', to: 'authors#create', as: 'create_author'
  get 'johannes', to: 'pages#johannes', as: 'johannes'

  get 'valerie_vaughn', to: 'pages#valerie_vaughn', as: 'valerie_vaughn'
  get 'vaughn_dashboard', to: 'pages#vaughn_dashboard', as: 'vaughn_dashboard'
  post 'editing_vaughn_page', to: 'johannes_page#editing_vaughn_page', as: 'editing_vaughn_page'

  get 'dave_garbutt', to: 'pages#dave_garbutt', as: 'dave_garbutt'
  get 'garbutt_dashboard', to: 'pages#garbutt_dashboard', as: 'garbutt_dashboard'
  post 'editing_garbutt_page', to: 'johannes_page#editing_garbutt_page', as: 'editing_garbutt_page'

  get 'james_finn', to: 'pages#james_finn', as: 'james_finn'
  get 'finn_dashboard', to: 'pages#finn_dashboard', as: 'finn_dashboard'
  post 'editing_finn_page', to: 'johannes_page#editing_finn_page', as: 'editing_finn_page'

  get 'muriz_serifovic', to: 'pages#muriz_serifovic', as: 'muriz_serifovicn'
  get 'serifovic_dashboard', to: 'pages#serifovic_dashboard', as: 'serifovic_dashboard'
  post 'editing_serifovic_page', to: 'johannes_page#editing_serifovic_page', as: 'editing_serifovic_page'

  get 'oliver_chalk', to: 'pages#oliver_chalk', as: 'oliver_chalk'
  get 'chalk_dashboard', to: 'pages#chalk_dashboard', as: 'chalk_dashboard'
  post 'editing_chalk_page', to: 'johannes_page#editing_chalk_page', as: 'editing_chalk_page'

  get 'harry_ven', to: 'pages#harry_ven', as: 'harry_ven'
  get 'ven_dashboard', to: 'pages#ven_dashboard', as: 'ven_dashboard'
  post 'editing_ven_page', to: 'johannes_page#editing_ven_page', as: 'editing_ven_page'

  get 'sylvia_clare', to: 'pages#sylvia_clare', as: 'sylvia_clare'
  get 'clare_dashboard', to: 'pages#clare_dashboard', as: 'clare_dashboard'
  post 'editing_clare_page', to: 'johannes_page#editing_clare_page', as: 'editing_clare_page'

  get 'steve_tannuzzo', to: 'pages#steve_tannuzzo', as: 'steve_tannuzzo'
  get 'tannuzzo_dashboard', to: 'pages#tannuzzo_dashboard', as: 'tannuzzo_dashboard'
  post 'editing_tannuzzo_page', to: 'johannes_page#editing_tannuzzo_page', as: 'editing_tannuzzo_page'

  get 'don_karp', to: 'pages#don_karp', as: 'don_karp'
  get 'karp_dashboard', to: 'pages#karp_dashboard', as: 'karp_dashboard'
  post 'editing_karp_page', to: 'johannes_page#editing_karp_page', as: 'editing_karp_page'

  get 'smita_vyas_kumar', to: 'pages#smita_vyas_kumar', as: 'smita_vyas_kumar'
  get 'vyas_kumar_dashboard', to: 'pages#vyas_kumar_dashboard', as: 'vyas_kumar_dashboard'
  post 'editing_vyas_kumar_page', to: 'johannes_page#editing_vyas_kumar_page', as: 'editing_vyas_kumar_page'

  get 'terijo', to: 'pages#terijo', as: 'terijo'
  get 'terijo_dashboard', to: 'pages#terijo_dashboard', as: 'terijo_dashboard'
  post 'editing_terijo_page', to: 'johannes_page#editing_terijo_page', as: 'editing_terijo_page'

  get 'artemis_jones', to: 'pages#artemis_jones', as: 'artemis_jones'
  get 'jones_dashboard', to: 'pages#jones_dashboard', as: 'jones_dashboard'
  post 'editing_jones_page', to: 'johannes_page#editing_jones_page', as: 'editing_jones_page'

  get 'daniel_teall', to: 'pages#daniel_teall', as: 'daniel_teall'
  get 'teall_dashboard', to: 'pages#teall_dashboard', as: 'teall_dashboard'
  post 'editing_teall_page', to: 'johannes_page#editing_teall_page', as: 'editing_teall_page'

  get 'amy_chai', to: 'pages#amy_chai', as: 'amy_chai'
  get 'chai_dashboard', to: 'pages#chai_dashboard', as: 'chai_dashboard'
  post 'editing_chai_page', to: 'johannes_page#editing_chai_page', as: 'editing_chai_page'

  get 'kristin_leonard', to: 'pages#kristin_leonard', as: 'kristin_leonard'
  get 'leonard_dashboard', to: 'pages#leonard_dashboard', as: 'leonard_dashboard'
  post 'editing_leonard_page', to: 'johannes_page#editing_leonard_page', as: 'editing_leonard_page'

  get 'esther_spurrill_jones', to: 'pages#esther_spurrill_jones', as: 'esther_spurrill_jones'
  get 'spurrill_jones_dashboard', to: 'pages#spurrill_jones_dashboard', as: 'spurrill_jones_dashboard'
  post 'editing_spurrill_jones_page', to: 'johannes_page#editing_spurrill_jones_page', as: 'editing_spurrill_jones_page'
  

  # statics
  get 'about', to: 'pages#about', as: 'about'
  get 'pricing', to: 'pages#pricing', as: 'pricing'
  get 'security_and_privacy', to: 'pages#security_and_privacy', as: 'privacy'
  get 'product_tour', to: 'pages#product_tour', as: 'product_tour'
  get 'do_now', to: 'pages#do_now', as: 'do_now'

  # signup/login
  get '/auth/:provider/callback', to: 'sessions#create', as: 'create_session'

  # user account page (for now)
  get 'user_account/:id', to: 'users#user_account', as: 'user_account'
  get 'quick_start', to: 'users#quick_start', as: 'quick_start'
  get 'quick_intro', to: 'users#quick_intro', as: 'quick_intro'

  # user account page (marcis version - work in progress)
  get 'account/:id', to: 'users#account', as: 'account'

  # create a contact
  post 'create_contact', to: 'contacts#create', as: 'create_contact'

  # create many contacts
  post 'create_many_contacts', to: 'contacts#create_many', as: 'create_many_contacts'
  post 'create_contacts_onboarding', to: 'contacts#create_many_onboarding', as: 'create_contacts_onboarding'

  # update a contact (this_month or interval)
  patch 'update_contact/:id', to: 'contacts#update', as: 'update_contact'

  # updating last contacted
  post 'update_last_contacted/:contact_id', to: 'contacts#update_last_contacted', as: 'update_last_contacted'

  # delete a contact
  delete 'delete_contact/:id', to: 'contacts#delete', as: 'delete_contact'

  # create or update profile
  post 'create_or_update_profile/:contact_id', to: 'profiles#create_or_update_profile', as: 'create_or_update_profile'

  # new reminder
  get 'set_reminder/:content', to: 'reminders#new', as: 'new_reminder'

  # create reminder
  post 'create_reminder', to: 'reminders#create', as: 'create_reminder'

  # backend
  get 'backend', to: 'pages#backend', as: 'backend'

  # logout
  delete '/logout', to: 'sessions#delete', as: 'logout'


  # pgae_builder_related
  post 'email_sub', to: 'johannes_page#email_subscriber', as: 'email_subscriber'
  post 'get_page', to: 'johannes_page#new_page_user', as: 'new_page_user'

end

app/models/user.rb
class User < ApplicationRecord

has_many :contacts, dependent: :destroy
has_many :reminders

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def quick_start
    if @user = current_user
      #pass
    else
      redirect_to root_path, notice: "please log in."
    end   
  end

  def quick_intro
    if @user = current_user
      #pass
    else
      redirect_to root_path, notice: "please log in."
    end
  end

  def user_account
  	if @user = current_user
		  @contacts = @user.contacts.order('updated_at DESC')
    	@contacts = @contacts.sort_by { |a| a.this_month ? 0 : 1 }
  	else
  		redirect_to root_path, notice: "please log in."
	  end
  end

  def account
  	if @user = current_user
		@contacts = @user.contacts.order('updated_at DESC')
    	@contacts = @contacts.sort_by { |a| a.this_month ? 0 : 1 }
  	else
  		redirect_to root_path, notice: "please log in."
    end
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div data-collapse="medium" data-animation="default" data-duration="400" class="navbar w-nav">
  <a href="/" class="brand w-nav-brand">
    <div class="logo-design">mind your network</div>
  </a>
  <nav role="navigation" class="nav-menu w-nav-menu">
    <a href="#" class="nav-link w-nav-link"><%= @user.name %></a>
    <a href="#" class="nav-link w-nav-link"><%= link_to 'Log Out', logout_path, method: :delete %></a></nav>
  <div class="w-nav-button">
    <div class="w-icon-nav-menu"></div>
  </div>
</div>

<div class="wrapper-form">
<div class="w-form">
  <%= form_for :contact, url: create_many_contacts_url do |f| %>
    <%= f.text_area :names, placeholder: "Add your Contacts. Separate multiple contacts with a comma.", id: "name", class: "text-field w-input" %>
    <%= f.submit "Add Contacs", class: "submit-button w-button" %>
  <% end %>
</div>
</div>

  <!--
  <form id="email-form" name="email-form" data-name="Email Form" class="form">
      <input type="text" class="text-field w-input" maxlength="256" name="name" data-name="Name" placeholder="Enter name of new contact" id="name" />
      <input type="submit" value="Add Contact" data-wait="Please wait..." class="submit-button w-button" />
    </form>
  -->

<div id="settings_updated" class="notice">
changes saved succesfully
</div>


<% @contacts.each do |contact| %>
  <%= form_for :contact, url: update_contact_url(id: contact.id),
          method: (:patch), remote: true, :authenticity_token => true  do |f| %>
          <div class="wrapper-contact">
            <div class="top-wrapper">
              <div class="wrapper-contact-info">
                <div class="title-wrapper">
                  <div class="name-contact"><%= contact.name %></div>
                </div>
              </div>
              <div class="wrapper-time">
                <div class="text-block-2">
                  <%= f.check_box :this_month, checked: contact.this_month, onchange: "click_submit_btn(this); return false;" %>
                  <span class="this-month">contact this month</span>

                  <span class="intervals">contact in</span>
                  <%= f.number_field :interval, value: contact.interval,
                          class: "interval_field", onchange: "click_submit_btn(this); return false;" %>
                  <span class="intervals">month intervals</span>

                  <%= f.submit "submit", class: "button-hide" %>
                </div>
              </div>
              <div class="div-block-5">
                <div class="bellow-function-wrapper">
                  <img src="https://daks2k3a4ib2z.cloudfront.net/59f72a5b04139300016ae066/5a04657e7e1de90001c9136a_notification.svg" class="organize-icon" />
                  <div class="text-below">
                    <%= link_to 'Notes', "#",
                          onclick: "display_comment_section(#{contact.id}); return false" %>
                  </div>
                </div>
                <div class="bellow-function-wrapper">
                  <img src="https://daks2k3a4ib2z.cloudfront.net/59f72a5b04139300016ae066/5a04656e9ea3b90001b7d926_calendar.svg" class="organize-icon" />
                  <div class="text-below"><%= link_to 'Schedule Reminder', new_reminder_path(content: contact.name) %></div>
                </div>
                <div class="bellow-function-wrapper">
                  <div class="text-below">
                    <%= link_to 'x', delete_contact_path(id: contact.id),
                              method: :delete, data: { confirm: 'Do you want to delete this contact?' } %>
                  </div>
                </div>
              </div>
            </div>
          </div>
  <% end %>

  <!-- comment setting sections -->
  <div id="<%= "comment_container_" + contact.id.to_s %>" class="note_taking_container">

    <div data-collapse="medium" data-animation="default" data-duration="400" class="navbar w-nav">
      <a href="/" class="brand w-nav-brand">
        <div class="logo-design">mind your network</div>
      </a>
      <nav role="navigation" class="nav-menu w-nav-menu">
    		<a href="#" class="nav-link w-nav-link"><%= link_to 'Back to Contacts', user_account_path(current_user) %></a>
    		<a href="#" class="nav-link w-nav-link"><%= link_to 'Log Out', logout_path, method: :delete %></a>
    	</nav>
      <div class="w-nav-button">
        <div class="w-icon-nav-menu"></div>
      </div>
    </div>
    <h3>Add notes</h3>
    <%= form_for :profile, :url => create_or_update_profile_url(contact_id: contact.id) do |form| %>
      <% if contact.profile %>
        <%= form.text_area :comment, value: contact.profile.comment %>
      <% else %>
        <%= form.text_area :comment, placeholder: "placeholder" %>
      <% end %> <br>
      <%= form.submit "Save note", class: "submit-button-2 w-button" %>
    <% end %>
  </div>

<% end %>

app/views/users/onboarding.html.erb
<div style="min-width: 1040px;">
<div data-collapse="medium" data-animation="default" data-duration="400"
    class="navbar w-nav" style="position: relative;">
  <a href="/" class="brand w-nav-brand">
      <div class="logo-design" style="font-size: 17px;"> MYN - <%= @user.name if @user %> </div>
  </a>
  <nav role="navigation" class="nav-menu w-nav-menu">  
    <div style="float: right;">

    </div>
  <div class="w-nav-button">
    <div class="w-icon-nav-menu"></div>
  </div>
</div>
</div>


<div class="add_contacts_container">
  
  <h3> Welcome <%= @user.first_name if @user %>! </h3>
  <p style="text-align: center; font-size: 24px; line-height: 1.38; margin-bottom; 40px; margin-top: 0px;"> 
  
    Who are 2-3 people (business or personal) <br>
    you would like to stay in touch with? <br> 
  </p>

    <%= form_for :contact, url: create_many_contacts_url do |f| %>
      <%= f.text_area :names, placeholder: "Elon Musk, Ayn Rand, Noam Chomsky ... (please separate by comma)", id: "onboarding_contacts_field" %> <br>
      <%= f.submit "Done", class: "add-button w-button" %>
    <% end %>

    <% if notice %>
      <br> <br>
      <p style="text-align: center; font-size: 20px; line-height: 1.28;"> 
         <%= notice %>
      </p>
   <% end %>
</div>

<div id="settings_updated" class="notice">
  changes saved succesfully.
</div>

app/views/users/quick_intro.html.erb
<div style="min-width: 1040px;">
<div data-collapse="medium" data-animation="default" data-duration="400"
    class="navbar w-nav" style="position: relative;">
  <a href="/" class="brand w-nav-brand">
      <div class="logo-design" style="font-size: 17px;"> MYN - <%= @user.name if @user %> </div>
  </a>
  <nav role="navigation" class="nav-menu w-nav-menu">  
    <div style="float: right;">

    </div>
  <div class="w-nav-button">
    <div class="w-icon-nav-menu"></div>
  </div>
</div>
</div>


<div class="add_contacts_container">
  <!-- <h3> Quick Intro </h3> -->
  <br>
  <p style="text-align: center; font-size: 24px; line-height: 1.38; margin-bottom; 40px; margin-top: 0px;">
    2 Minute Intro - What you can do with MYN 
  </p> <br>

  <iframe width="560" height="315" src="https://www.youtube.com/embed/Z9-01xCqYaI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen style="border: 1px solid lightgrey;"></iframe> <br> <br>

    <%= link_to 'Continue to Dashboard', user_account_path(current_user), class: "add-button w-button" %>

    <% if notice %>
      <br> <br>
      <p style="text-align: center; font-size: 20px; line-height: 1.28;"> 
         <%= notice %>
      </p>
   <% end %>
</div>

app/views/users/quick_start.html.erb
<div style="min-width: 1040px;">
<div data-collapse="medium" data-animation="default" data-duration="400"
    class="navbar w-nav" style="position: relative;">
  <a href="/" class="brand w-nav-brand">
      <div class="logo-design" style="font-size: 17px;"> MYN - <%= @user.name if @user %> </div>
  </a>
  <nav role="navigation" class="nav-menu w-nav-menu">  
    <div style="float: right;">

    </div>
  <div class="w-nav-button">
    <div class="w-icon-nav-menu"></div>
  </div>
</div>
</div>


<div class="add_contacts_container">
  <h3> Welcome <%= @user.first_name if @user %>! </h3>
  <p style="text-align: center; font-size: 24px; line-height: 1.38; margin-bottom; 40px; margin-top: 0px;"> 
    Who are 3-5 people - business or personal - <br>
    you would like to stay in contact with? <br> 
  </p>

    <%= form_for :contact, url: create_contacts_onboarding_url do |f| %>
      <%= f.text_area :names, placeholder: "Elon Musk, Ayn Rand, Noam Chomsky ... (please separate by comma)", id: "onboarding_contacts_field" %> <br>
      <%= f.submit "Done", class: "add-button w-button" %> <br> <br>
      <%= link_to 'skip for now', quick_intro_path, 
              style: "text-decoration: underline; color: grey;" %>
    <% end %>

    <% if notice %>
      <br> <br>
      <p style="text-align: center; font-size: 20px; line-height: 1.28;"> 
         <%= notice %>
      </p>
   <% end %>
</div>

app/views/users/user_account.html.erb
<div style="min-width: 1040px;">
<div data-collapse="medium" data-animation="default" data-duration="400"
    class="navbar w-nav" style="position: relative;">
  <a href="/" class="brand w-nav-brand">
      <div class="logo-design" style="font-size: 17px;"> MYN - <%= @user.name if @user %> </div>
  </a>
  <nav role="navigation" class="nav-menu w-nav-menu">  
    <div style="float: right;">
    <%= link_to 'About Us', about_path, class: "header_btn" %>
    <%= link_to 'Pricing', pricing_path, class: "header_btn" %>
    <%= link_to 'Security', privacy_path, class: "header_btn" %>
    <%= link_to '2 Min Product Tour', product_tour_path, class: "header_btn_outer" %>
    <%= link_to 'Log Out', logout_path, method: :delete, class: "header_btn_outer" %>
    </div>
  <div class="w-nav-button">
    <div class="w-icon-nav-menu"></div>
  </div>
</div>
</div>


<div class="add_contacts_container">
  <p style="text-align: center; font-size: 24px; line-height: 1.38; margin-bottom; 40px; margin-top: 43px;"> 
    Add Your Contacts
  </p>
    <%= form_for :contact, url: create_many_contacts_url do |f| %>
      <%= f.text_area :names, placeholder: "Elon Musk, Boris Johnson, Ayn Rand, Noam Chomsky ... etc.", id: "add_contacts_field" %> <br>
      <%= f.submit "Add", class: "add-button w-button" %>
    <% end %>

    <% if notice %>
      <br> <br>
      <p style="text-align: center; font-size: 20px; line-height: 1.28; margin-bottom: -35px;"> 
         <%= notice %>
      </p>
   <% end %>
</div>

<div id="settings_updated" class="notice">
  changes saved succesfully.
</div>

<div class="table_container">
  <div style="margin-bottom: -20px;">
    <div style="display: inline-block; width: 230px; max-width: 230px; font-weight: bold; text-decoration: underline; padding-left: 60px;">
      Name
    </div>

    <div style="display: inline-block; width: 130px; max-width: 130px; font-weight: bold; text-decoration: underline;">
      This Month
    </div> 
  
    <div style="display: inline-block; width: 176px; max-width: 176px; font-weight: bold; text-decoration: underline;">
      Contact Intervals
    </div> 

    <div style="display: inline-block; width: 186px; max-width: 186px; font-weight: bold; text-decoration: underline;"> 
      E-Mail Reminders
    </div>
    
    <div style="display: inline-block; width: 166px; max-width: 166px; font-weight: bold; text-decoration: underline;"> 
      Tags & Notes
    </div>
    
    <!--
    <div style="display: inline-block; width: 112px; max-width: 112px; font-weight: bold; text-decoration: underline;">
      Online Scan
    </div>
    --> 
  </div>

  <% if !@contacts.empty? %>
  
  <% @contacts.each do |contact| %>
    <p style="margin-bottom: 55px;"> 
      <%= form_for :contact, url: update_contact_url(id: contact.id),
          method: (:patch), remote: true, authenticity_token: true do |f| %>

        
        <div style="position: relative; display: inline-block; width: 234px; max-width: 234px; font-size: 15px; padding-left: 60px;"> 
          <strong> <%= contact.name %> </strong>
          <div style="font-size: 12px; position: absolute; top: 20px; cursor: pointer;">
            <%= contact.profile.tags if contact.profile && contact.profile.tags %>
          </div>
        </div>

        <div style="display: inline-block; width: 132px; max-widths: 132px;">
          <%= f.check_box :this_month, checked: contact.this_month, style: "margin-left: 33px;",
              onchange: "click_submit_btn(this); return false;", class: "this_month_check_box" %>
          <%= f.submit "this month.", style: "display: none;" %>
        </div>
      
        <div style="display: inline-block; width: 172px; max-width: 172px;"> 
          Every
          <%= f.number_field :interval, value: contact.interval, style: "width: 34px;",
              onchange: "click_submit_btn(this); return false;", class: "interval_field" %> 
          Months
          <%= f.submit "set", style: "display: none;" %>
        </div>

        <div style="display: inline-block; width: 186px; max-width: 186px;">
          <%= link_to 'Set Reminder', new_reminder_path(content: contact.name),
              id: "set_reminder_btn" %>
        </div>

        <div style="display: inline-block; width: 165px; max-width: 165px;">
          <%= link_to 'Tags & Notes', "#", id: "manage_contact_btn",
              onclick: "display_comment_section(#{contact.id}); return false",
              style: "padding: 5px 22px;" %>
        </div>
  
        <div style="position: relative; display: inline-block; width: 140px; max-width: 140px;">
          <%= link_to 'Mark as done', update_last_contacted_url(contact_id: contact.id),
              method: :post, id: "manage_contact_btn", style: "padding: 5px 12px;" %>
          <div style="position: absolute; top: 24px; font-size: 12px; padding-left: 22px;">
            <% if contact.last_contacted %>
              <%= contact.last_contacted.strftime("%d %B") %>
            <% end %>
          </div>
        </div>
  
        <!--
        <div style="display: inline-block; width: 145px; max-width: 145px;">
          <%= f.text_field :email, value: contact.email, style: "width: 155px;",
              onkeyup: "click_submit_btn(this); return false;", placeholder: "contact's email" %> 
          <%= f.submit "set", style: "display: none;" %>
        </div>
        -->
      <% end %>
    </p>


    <!-- Tags & Notes -->
    <div id="<%= "comment_container_" + contact.id.to_s %>" class="note_taking_container">
    
      <div data-collapse="medium" data-animation="default" data-duration="400"
          class="navbar w-nav" style="position: relative;">
        <a href="/" class="brand w-nav-brand">
            <div class="logo-design" style="font-size: 17px;"> MYN - <%= @user.name if @user %> </div>
        </a>
        <nav role="navigation" class="nav-menu w-nav-menu">  
          <div style="float: right;">
          <%= link_to 'About Us', about_path, class: "header_btn" %>
          <%= link_to 'Pricing', pricing_path, class: "header_btn" %>
          <%= link_to 'Security', privacy_path, class: "header_btn" %>
          <%= link_to 'Go Back to Dashboard', root_path, class: "header_btn_outer" %>
          <!--
          <%= link_to 'Delete This Contact', delete_contact_path(id: contact.id), method: :delete, data: { confirm: 'Sure?' }, class: "header_btn_outer" %>
          -->
          </div>
        <div class="w-nav-button">
          <div class="w-icon-nav-menu"></div>
        </div>
      </div> <br> <br> <br>


      <%= form_for :profile, :url => create_or_update_profile_url(contact_id: contact.id) do |f| %>
        <p> <strong> Tags - <%= contact.name %> </strong> <br>
          please separate with commas <br>
          tag, tag, tag
        </p>

        <%= f.text_field :tags, placeholder: "...",
          value: (contact.profile.tags if contact.profile && contact.profile.tags), class: "add_note_field", style: "height: 30px;" %> <br> <br> <br>

        <p> <strong> Note - <%= contact.name %> </strong> <br> Relevant Info? <br>
        Work? Interests? Hobbies? etc. </p>

        <%= f.text_area :comment, placeholder: "...", 
            value: (contact.profile.comment if contact.profile && contact.profile.comment),
                class: "add_note_field" %> <br>

        <%= f.submit "save", class: "submit-button-2 w-button", 
              style: "padding: 2px 26px; margin-top: 18px;" %> <br> <br>
      <% end %>
      

      <%= link_to 'Back To Dashboard', user_account_path(current_user), style: "text-decoration: underline;" %> |
      <%= link_to 'Delete this Contact', delete_contact_path(id: contact.id), method: :delete, data: { confirm: 'Sure?' }, style: "text-decoration: underline;" %>
    </div>
  <% end %>


  <% else %>
    <!-- when there are no contacts yet -->
    <h3 id="empty_contacts_msg">
      <%= link_to 'Product Tour', "https://www.youtube.com/watch?v=Z9-01xCqYaI&feature=youtu.be",
            target: "_blank", id: "watch_explainer_btn", style: "padding: 15px 34px" %> 
    </h3>
  <% end %>

</div> 