config/routes.rb
Rails.application.routes.draw do

  # root
  root 'pages#home'

  # wordgates
  get 'get_started', to: 'pages#get_started', as: 'get_started'
  get 'get_page', to: 'pages#get_page', as: 'get_page'
  get 'get_your_page', to: 'pages#get_your_page', as: 'get_your_page'
  get 'done', to: 'pages#thank_you', as: 'thank_you'
  resources :writers

  get 'how_it_works', to: 'pages#how_it_works', as: 'how_it_works'
  get 'features', to: 'pages#features', as: 'features'
  get 'about_us', to: 'pages#about_us', as: 'about_us'
  get 'our_pricing', to: 'pages#our_pricing', as: 'our_pricing'


  # course
  get 'course', to: 'course#lesson_two', as: 'lesson_intro'
  get 'lesson_one', to: 'course#lesson_one', as: 'lesson_one'
  get 'lesson_two', to: 'course#lesson_two', as: 'lesson_two'
  get 'lesson_three', to: 'course#lesson_three', as: 'lesson_three'
  get 'lesson_four', to: 'course#lesson_four', as: 'lesson_four'
  get 'lesson_five', to: 'course#lesson_five', as: 'lesson_five'
  get 'lesson_six', to: 'course#lesson_six', as: 'lesson_six'
  get 'lesson_seven', to: 'course#lesson_seven', as: 'lesson_seven'
  get 'lesson_eight', to: 'course#lesson_eight', as: 'lesson_eight'

  post 'student_question', to: 'course#student_question', as: 'student_question'
  get 'message_sent', to: 'course#message_sent', as: 'message_sent'


  post 'get_started', to: 'authors#create', as: 'create_author'
  get 'johannes', to: 'pages#johannes', as: 'johannes'

  get 'valerie_vaughn', to: 'pages#valerie_vaughn', as: 'valerie_vaughn'
  get 'vaughn_dashboard', to: 'pages#vaughn_dashboard', as: 'vaughn_dashboard'
  post 'editing_vaughn_page', to: 'johannes_page#editing_vaughn_page', as: 'editing_vaughn_page'

  get 'dave_garbutt', to: 'pages#dave_garbutt', as: 'dave_garbutt'
  get 'garbutt_dashboard', to: 'pages#garbutt_dashboard', as: 'garbutt_dashboard'
  post 'editing_garbutt_page', to: 'johannes_page#editing_garbutt_page', as: 'editing_garbutt_page'

  get 'james_finn', to: 'pages#james_finn', as: 'james_finn'
  get 'finn_dashboard', to: 'pages#finn_dashboard', as: 'finn_dashboard'
  post 'editing_finn_page', to: 'johannes_page#editing_finn_page', as: 'editing_finn_page'

  get 'muriz_serifovic', to: 'pages#muriz_serifovic', as: 'muriz_serifovicn'
  get 'serifovic_dashboard', to: 'pages#serifovic_dashboard', as: 'serifovic_dashboard'
  post 'editing_serifovic_page', to: 'johannes_page#editing_serifovic_page', as: 'editing_serifovic_page'

  get 'oliver_chalk', to: 'pages#oliver_chalk', as: 'oliver_chalk'
  get 'chalk_dashboard', to: 'pages#chalk_dashboard', as: 'chalk_dashboard'
  post 'editing_chalk_page', to: 'johannes_page#editing_chalk_page', as: 'editing_chalk_page'

  get 'harry_ven', to: 'pages#harry_ven', as: 'harry_ven'
  get 'ven_dashboard', to: 'pages#ven_dashboard', as: 'ven_dashboard'
  post 'editing_ven_page', to: 'johannes_page#editing_ven_page', as: 'editing_ven_page'

  get 'sylvia_clare', to: 'pages#sylvia_clare', as: 'sylvia_clare'
  get 'clare_dashboard', to: 'pages#clare_dashboard', as: 'clare_dashboard'
  post 'editing_clare_page', to: 'johannes_page#editing_clare_page', as: 'editing_clare_page'

  get 'steve_tannuzzo', to: 'pages#steve_tannuzzo', as: 'steve_tannuzzo'
  get 'tannuzzo_dashboard', to: 'pages#tannuzzo_dashboard', as: 'tannuzzo_dashboard'
  post 'editing_tannuzzo_page', to: 'johannes_page#editing_tannuzzo_page', as: 'editing_tannuzzo_page'

  get 'don_karp', to: 'pages#don_karp', as: 'don_karp'
  get 'karp_dashboard', to: 'pages#karp_dashboard', as: 'karp_dashboard'
  post 'editing_karp_page', to: 'johannes_page#editing_karp_page', as: 'editing_karp_page'

  get 'smita_vyas_kumar', to: 'pages#smita_vyas_kumar', as: 'smita_vyas_kumar'
  get 'vyas_kumar_dashboard', to: 'pages#vyas_kumar_dashboard', as: 'vyas_kumar_dashboard'
  post 'editing_vyas_kumar_page', to: 'johannes_page#editing_vyas_kumar_page', as: 'editing_vyas_kumar_page'

  get 'terijo', to: 'pages#terijo', as: 'terijo'
  get 'terijo_dashboard', to: 'pages#terijo_dashboard', as: 'terijo_dashboard'
  post 'editing_terijo_page', to: 'johannes_page#editing_terijo_page', as: 'editing_terijo_page'

  get 'artemis_jones', to: 'pages#artemis_jones', as: 'artemis_jones'
  get 'jones_dashboard', to: 'pages#jones_dashboard', as: 'jones_dashboard'
  post 'editing_jones_page', to: 'johannes_page#editing_jones_page', as: 'editing_jones_page'

  get 'daniel_teall', to: 'pages#daniel_teall', as: 'daniel_teall'
  get 'teall_dashboard', to: 'pages#teall_dashboard', as: 'teall_dashboard'
  post 'editing_teall_page', to: 'johannes_page#editing_teall_page', as: 'editing_teall_page'

  get 'amy_chai', to: 'pages#amy_chai', as: 'amy_chai'
  get 'chai_dashboard', to: 'pages#chai_dashboard', as: 'chai_dashboard'
  post 'editing_chai_page', to: 'johannes_page#editing_chai_page', as: 'editing_chai_page'

  get 'kristin_leonard', to: 'pages#kristin_leonard', as: 'kristin_leonard'
  get 'leonard_dashboard', to: 'pages#leonard_dashboard', as: 'leonard_dashboard'
  post 'editing_leonard_page', to: 'johannes_page#editing_leonard_page', as: 'editing_leonard_page'

  get 'esther_spurrill_jones', to: 'pages#esther_spurrill_jones', as: 'esther_spurrill_jones'
  get 'spurrill_jones_dashboard', to: 'pages#spurrill_jones_dashboard', as: 'spurrill_jones_dashboard'
  post 'editing_spurrill_jones_page', to: 'johannes_page#editing_spurrill_jones_page', as: 'editing_spurrill_jones_page'
  

  # statics
  get 'about', to: 'pages#about', as: 'about'
  get 'pricing', to: 'pages#pricing', as: 'pricing'
  get 'security_and_privacy', to: 'pages#security_and_privacy', as: 'privacy'
  get 'product_tour', to: 'pages#product_tour', as: 'product_tour'
  get 'do_now', to: 'pages#do_now', as: 'do_now'

  # signup/login
  get '/auth/:provider/callback', to: 'sessions#create', as: 'create_session'

  # user account page (for now)
  get 'user_account/:id', to: 'users#user_account', as: 'user_account'
  get 'quick_start', to: 'users#quick_start', as: 'quick_start'
  get 'quick_intro', to: 'users#quick_intro', as: 'quick_intro'

  # user account page (marcis version - work in progress)
  get 'account/:id', to: 'users#account', as: 'account'

  # create a contact
  post 'create_contact', to: 'contacts#create', as: 'create_contact'

  # create many contacts
  post 'create_many_contacts', to: 'contacts#create_many', as: 'create_many_contacts'
  post 'create_contacts_onboarding', to: 'contacts#create_many_onboarding', as: 'create_contacts_onboarding'

  # update a contact (this_month or interval)
  patch 'update_contact/:id', to: 'contacts#update', as: 'update_contact'

  # updating last contacted
  post 'update_last_contacted/:contact_id', to: 'contacts#update_last_contacted', as: 'update_last_contacted'

  # delete a contact
  delete 'delete_contact/:id', to: 'contacts#delete', as: 'delete_contact'

  # create or update profile
  post 'create_or_update_profile/:contact_id', to: 'profiles#create_or_update_profile', as: 'create_or_update_profile'

  # new reminder
  get 'set_reminder/:content', to: 'reminders#new', as: 'new_reminder'

  # create reminder
  post 'create_reminder', to: 'reminders#create', as: 'create_reminder'

  # backend
  get 'backend', to: 'pages#backend', as: 'backend'

  # logout
  delete '/logout', to: 'sessions#delete', as: 'logout'


  # pgae_builder_related
  post 'email_sub', to: 'johannes_page#email_subscriber', as: 'email_subscriber'
  post 'get_page', to: 'johannes_page#new_page_user', as: 'new_page_user'

end

app/views/pages/aa_dash_layout.html.erb
<%= link_to "Back to Site", sylvia_clare_path, id: "dashboard_link" %> 

<div class="container-fluid">
  <div class="central_container"> 		

  	<div class="left_side_container">
	  	<%= image_tag "https://cdn-images-1.medium.com/fit/c/100/100/1*fK176WLzCPb96o8AMKdmCw.jpeg", id: "profile_image" %>
	</div>

  	<div id="middle_container" class="middle_container" style="width: 570px;">  	
  		<% if notice %> <h1 class="name_title" style="margin-bottom: 28px"> <%= notice %> </h1> <% end %>

		<h1 class="name_title"> Dashboard </h1>		
		<p style="background-color: #F5EFE6; padding-left: 8px;"> Note: The posts on your site sync with your Medium every 24 hours. </p>

		<h3 class="title" style="margin-bottom: 8px; margin-top: 35px;"> Choose your Features </h3>
		<!-- <p> Unckeck any features you do not want. </p> -->


		<%= form_for :user_settings, url: editing_clare_page_path do |f| %>
            <%= f.check_box :portrait_feature, checked: @authors_settings.portrait_feature %> Your Image on the Left <br>
            <%= f.check_box :about_feature, checked: @authors_settings.about_feature %> "About Me" Section <br>
            <!-- <%= f.check_box :this_month, checked: true %> "Posts" Section <br> -->
            <%= f.check_box :email_subscription_feature, checked: @authors_settings.email_subscription_feature %> Subscribe to Email-Updates Box <br> 
            <%= f.check_box :social_icons_features, checked: @authors_settings.social_icons_features %> Social Icons - Twitter, Medium <br>
            <%= f.check_box :contact_feature, checked: @authors_settings.contact_feature %> Contact Me Box <br>
			<%= f.submit "Apply Changes", style: "font-size: 14px; margin-top: 8px;" %>
		 	<br>

			<h3 class="title" style="margin-bottom: 8px; margin-top: 40px;"> Your "About Me" Section </h3>
            Title: <br>
            <%= f.text_field :about_title, value: @authors_settings.about_title, style: "width: 215px;" %> <br>
            Content: <br>
            <%= f.text_area :about_content, value: @authors_settings.about_content, style: "width: 215px; height: 105px;" %> <br>
			<%= f.submit "Apply Changes", style: "font-size: 14px; margin-top: 8px;" %>
		 	<br>

			<h3 class="title" style="margin-bottom: 8px; margin-top: 40px;">
				Your Posts 
			</h3>
			<p> 
				Unckeck those posts you want to hide. <br>
				An option to publish more posts here which <br> are not on your Medium is coming soon.
			</p>

            <%= f.check_box :post_one, checked: @authors_settings.post_one %> What is a Writer?  <br>
            <%= f.check_box :post_two, checked: @authors_settings.post_two %> Instant Karma’s going to get you <br>
            <%= f.check_box :post_three, checked: @authors_settings.post_three %> Writing to Find Your Best <br>
            <%= f.check_box :post_four, checked: @authors_settings.post_four %> Writing my way back to love <br> 
            <%= f.check_box :post_five, checked: @authors_settings.post_five %> Brief Encounter <br>
			<%= f.submit "Apply Changes", style: "font-size: 14px; margin-top: 8px;" %>
		<% end %> <br>

		<h3 class="title" style="margin-bottom: 8px; margin-top: 20px;"> Your Images </h3>
		<p> 
			An option to change your image
			and the site's <br> background image
			is coming within the next few days.
		</p>

		<div class="powered_by_dashboard"> Powered by WordGates | The Home of Writers. </div>
  	</div>
  </div>
</div>


<style type="text/css">
	body {
	  margin: 0;
	  padding-bottom: 20px;
	  background: url("https://pbs.twimg.com/profile_images/874184738210275328/lqpLD-zW_400x400.jpg") no-repeat center center fixed; 
	  -webkit-background-size: cover;
	  -moz-background-size: cover;
	  -o-background-size: cover;
	  background-size: cover;
	}	
</style>

app/views/pages/chai_dashboard.html.erb
<%= link_to "Back to Site", amy_chai_path, id: "dashboard_link" %> 

<div class="container-fluid">
  <div class="central_container"> 		

  	<div class="left_side_container">
	  	<%= image_tag "#{@image_of_author}", id: "profile_image" %>
	</div>

  	<div id="middle_container" class="middle_container" style="width: 570px;">  	
  		<% if notice %> <h1 class="name_title" style="margin-bottom: 28px"> <%= notice %> </h1> <% end %>

		<h1 class="name_title"> Dashboard </h1>		
		<p style="background-color: #F5EFE6; padding-left: 8px;"> Note: The posts on your site sync with your Medium every 24 hours. </p>

		<h3 class="title" style="margin-bottom: 8px; margin-top: 35px;"> Choose your Features </h3>
		<!-- <p> Unckeck any features you do not want. </p> -->


		<%= form_for :user_settings, url: editing_chai_page_path do |f| %>
            <%= f.check_box :portrait_feature, checked: @authors_settings.portrait_feature %> Your Image on the Left <br>
            <%= f.check_box :about_feature, checked: @authors_settings.about_feature %> "About Me" Section <br>
            <!-- <%= f.check_box :this_month, checked: true %> "Posts" Section <br> -->
            <%= f.check_box :email_subscription_feature, checked: @authors_settings.email_subscription_feature %> Subscribe to Email-Updates Box <br> 
            <%= f.check_box :social_icons_features, checked: @authors_settings.social_icons_features %> Social Icons - Twitter, Medium <br>
            <%= f.check_box :contact_feature, checked: @authors_settings.contact_feature %> Contact Me Box <br>
			<%= f.submit "Apply Changes", style: "font-size: 14px; margin-top: 8px;" %>
		 	<br>

			<h3 class="title" style="margin-bottom: 8px; margin-top: 40px;"> Your "About Me" Section </h3>
            Title: <br>
            <%= f.text_field :about_title, value: @authors_settings.about_title, style: "width: 215px;" %> <br>
            Content: <br>
            <%= f.text_area :about_content, value: @authors_settings.about_content, style: "width: 215px; height: 105px;" %> <br>
			<%= f.submit "Apply Changes", style: "font-size: 14px; margin-top: 8px;" %>
		 	<br>

			<h3 class="title" style="margin-bottom: 8px; margin-top: 40px;">
				Your Posts 
			</h3>
			<p> 
				Unckeck those posts you want to hide. <br>
				An option to publish more posts here which <br> are not on your Medium is coming soon.
			</p>

            <%= f.check_box :post_one, checked: @authors_settings.post_one %>  <%= @title1 %> <br>
            <%= f.check_box :post_two, checked: @authors_settings.post_two %>  <%= @title2 %> <br>
            <%= f.check_box :post_three, checked: @authors_settings.post_three %> <%= @title3 %> <br>
            <%= f.check_box :post_four, checked: @authors_settings.post_four %> <%= @title4 %> <br> 
            <%= f.check_box :post_five, checked: @authors_settings.post_five %> <%= @title5 %> <br>
			<%= f.submit "Apply Changes", style: "font-size: 14px; margin-top: 8px;" %>
		<% end %> <br>

		<h3 class="title" style="margin-bottom: 8px; margin-top: 20px;"> Your Images </h3>
		<p> 
			An option to change your image
			and the site's <br> background image
			is coming within the next few days.
		</p>

		<div class="powered_by_dashboard"> Powered by WordGates | The Home of Writers. </div>
  	</div>
  </div>
</div>


<style type="text/css">
	body {
	  margin: 0;
	  padding-bottom: 20px;
	  background: url(<%= @background_image %>) no-repeat center center fixed;
	  -webkit-background-size: cover;
	  -moz-background-size: cover;
	  -o-background-size: cover;
	  background-size: cover;
	}	
</style>

app/views/pages/layout_for_person.html.erb
<div class="container_of_page">
	
	<!--
	<div class="the_get_page_btn">
		<p onclick="show_get_page();">
			Get a page like this.	
		</p>
	</div> -->

	<div class="left_ctn">
		<%= image_tag "dave_garbutt.png" %> <br> <br>
	</div>


	<div class="right_ctn">

		<p class="get_page_btn">
			<span style="font-size: 13px;"> <span style="text-decoration: underline;"> Notifier </span> <br> Notify me by Email <br> when a new post comes out: </span>
			<%= form_for :email_subscriber, url: email_subscriber_url do |f| %>
				<%= f.text_field :email, placeholder: "me@myemail.com",
						style: "width: 170px; height: 28px; margin: 0px 13px 3px 13px;" %> <br>
				<%= f.submit "done", style: "cursor: pointer; float: right;
						margin-right: 17px" %>
			<% end %>
		</p>
		<br> <br>

		<p class="get_page_btn">
			<span style="font-size: 14px; text-decoration: underline;"> My Social </span>
			<br>
			<a href="https://medium.com/@">
				<i class="fab fa-medium-m" style="font-size: 39px; margin-right: 8px; padding-top: 14px;"></i>
			</a>
			<a href="https://twitter.com/">
				<i class="fab fa-twitter" style="font-size: 39px; padding-top: 14px"></i>
			</a>
		</p>
		<br>

		<p class="get_page_btn">
			<span style="font-size: 13px;"> <span style="text-decoration: underline;"> Contact </span> <br>
			Write me directly below: </span>
			<%= form_for :email_subscriber, url: email_subscriber_url do |f| %>
				<%= f.text_area :email, placeholder: "my message",
						style: "width: 170px; height: 85px; margin: 0px 13px;" %> <br>
				<%= f.submit "send", style: "cursor: pointer; float: right;
						margin-right: 17px" %>
			<% end %>
		</p>
	</div>


	<div id="default_page_body">
		<% if notice %>
			<h1 style="margin-bottom: -48px;"> <%= notice %> </h1>
		<% end %>

		<h1> Dave Garbutt </h2>
		<h3 style="text-decoration: underline;"> Me in 10 seconds </h3>
		<p>
			Retired. <br>
			Former Senior Consultant at NNIT A/S. <br>
		 	Former SAS computing environment designer and consultant at Novartis AG. <br>
		 	Former Postdoc at University of Reading. <br>
		 	Living in Basel. <br>
		 	From London. <br>
		</p> <br>

		<h3 style="text-decoration: underline;"> Posts <h3>
		<p class="title_of_work" onclick='show_piece("piece_zero");'> </p>
		<p class="title_of_work" onclick='show_piece("piece_one");'> </p>
		<p class="title_of_work" onclick='show_piece("piece_two");'> </p>
		<p class="title_of_work" onclick='show_piece("piece_three");'> </p>
		<p class="title_of_work" onclick='show_piece("piece_four");'> </p>
		<p class="title_of_work" onclick='show_piece("piece_five");'> </p>
		<p class="title_of_work" onclick='show_piece("piece_six");'> </p>
		<p class="title_of_work" onclick='show_piece("piece_seven");'> </p>
	</div>


	<div class="piece_of_work" id="piece_zero">
		<h1 onclick='show_default("piece_zero")' class="go_back_btn">
			<i class="fas fa-arrow-left" style="margin-right: 3px;"></i> Go Back 
		</h1>
		<h3 class="piece_header"> </h3>		
		<p>

		</p>
	</div>


	<div class="piece_of_work" id="piece_one">
		<h1 onclick='show_default("piece_one")' class="go_back_btn">
			<i class="fas fa-arrow-left" style="margin-right: 3px;"></i> Go Back 
		</h1>
		<h3 class="piece_header"> </h3>		
		<p>

		</p>
	</div>


	<div class="piece_of_work" id="piece_two">
		<h1 onclick='show_default("piece_two")' class="go_back_btn">
			<i class="fas fa-arrow-left" style="margin-right: 3px;"></i> Go Back 
		</h1>
		<h3 class="piece_header"> </h3>		
		<p>

		</p>
	</div>


	<div class="piece_of_work" id="piece_three">
		<h1 onclick='show_default("piece_three")' class="go_back_btn">
			<i class="fas fa-arrow-left" style="margin-right: 3px;"></i> Go Back 
		</h1>
		<h3 class="piece_header"> </h3>		
		<p>

		</p>
	</div>


	<div class="piece_of_work" id="piece_four">
		<h1 onclick='show_default("piece_four")' class="go_back_btn">
			<i class="fas fa-arrow-left" style="margin-right: 3px;"></i> Go Back 
		</h1>
		<h3 class="piece_header"> </h3>		
		<p>

		</p>
	</div>


	<div class="piece_of_work" id="piece_five">
		<h1 onclick='show_default("piece_five")' class="go_back_btn">
			<i class="fas fa-arrow-left" style="margin-right: 3px;"></i> Go Back 
		</h1>
		<h3 class="piece_header"> </h3>		
		<p>

		</p>
	</div>


	<div class="piece_of_work" id="piece_six">
		<h1 onclick='show_default("piece_six")' class="go_back_btn">
			<i class="fas fa-arrow-left" style="margin-right: 3px;"></i> Go Back 
		</h1>
		<h3 class="piece_header"> </h3>		
		<p>

		</p>
	</div>


	<div class="piece_of_work" id="piece_seven">
		<h1 onclick='show_default("piece_seven")' class="go_back_btn">
			<i class="fas fa-arrow-left" style="margin-right: 3px;"></i> Go Back 
		</h1>
		<h3 class="piece_header"> </h3>		
		<p>

		</p>
	</div>



	<div id="get_page_like_this">
		<h1 onclick='show_default("get_page_like_this")' class="go_back_btn">
			Back 
		</h1>

		<h3 class="piece_header" style="margin-top: 20px; text-decoration: underline;"> 
			Generate your own site:
			<!-- All you need to do. -->
		 </h3>		

		<!--
		<h3> The literally-no-effort way to start representing yourself online 
		& collect Emails from followers/fans. </h3>		
		-->
		<p>
			<%= form_for :new_page_user, url: new_page_user_url do |f| %>
				<p> Email address <br>
				<%= f.text_field :email, placeholder: "myemail@example.com" %> <br>
				</p>
				<p> Link to your Medium <br> <%= f.text_field :medium_link, placeholder: "medium.com/@myName" %> <br>
 					</p>
				<%= f.submit "done", style: "cursor: pointer;" %>
			<% end %>
			<br> <br>

			<h3 style="text-decoration: underline;"> How it works </h3>
			Submitting the form will use the info on your
			 Medium profile to generate your own site in the same layout as the site that
			I have made for myself. It's literally no effort. Submit and you're done.
			<br> <br>
			<!--
			If you can afford it, I'd like to charge 2.99£ / month 
			- mostly because maintenance requires work.
			But if you can't afford it, no worries.
 			<br> <br>

			Any questions or requests? Please get in touch! <br> 
			<a href="mailto:joseikowsky@gmail.com?Subject=Hi" id="my_email" target="_top"> joseikowsky@gmail.com </a> <br> <br>
			Best, <br> <br>
			Johannes
			-->
		</p>
	</div>

	<div class="my_page_footer">
		<%= link_to "Find me on Twitter", "https://twitter.com/", style: "color: black; font-weight: bold;" %> |
		<%= link_to "Find me on Medium", "https://medium.com/@", style: "color: black; font-weight: bold;" %>
	</div>
</div>


<style type="text/css">
	body {
	  margin: 0;
	  padding-bottom: 20px;
	  background: url("https://pbs.twimg.com/profile_banners/958729147408310272/1517922790/1500x500") no-repeat center center fixed; 
	  -webkit-background-size: cover;
	  -moz-background-size: cover;
	  -o-background-size: cover;
	  background-size: cover;
	}

	.container_of_page{
	  width: 474px;
	  margin: 66px auto;
	  background-color: white;
	  position: relative;
	  padding: 0px 22px 8px 22px;
	}

	h1{
		font-size: 26px;
		font-weight: bold;
		padding-bottom: 9px;
		padding-top: 10px;
		margin-top: 75px;
		margin-bottom: 14px;
		border-bottom: 1px solid #eee;}

	p{
		font-size: 16px;
		line-height: 1.6;
		margin-bottom: 16px;}

	#my_email:hover{
		text-decoration: underline;
	}

	.right_ctn{
		position: absolute;
    	right: -208px;
    	top: 0px;
    	width: 200px;
	}
	

	.the_get_page_btn{
		position: fixed;
		top: 12px;
		right: 12px;
		width: 180px;
		height: 44px;
		cursor: pointer;
		font-size: 14px;
		font-weight: bold;
		text-align: center;
		border: 1px solid lightGrey;
		background-color: #FFE9AF;
		padding: 8px;
	}

	.get_page_btn{
		width: 85%;
		margin-left: 12px;
		margin-bottom: 5px;
		cursor: pointer;
		padding: 15px 15px;
		font-size: 14px;
		font-weight: bold;
		text-align: center;
		background-color: white;
		border: 1px solid lightGrey;
	}

	.mini_slogan{
		margin-left: 11px;
		font-size: 13px;
	}

	.left_ctn{
		position: absolute;
    	left: -222px;
    	top: 0px;		
	}

	img{
		margin: 15px 10% 15px 10%;
		border: 1px solid #9F9F9F;
		margin-bottom: 26px;
		width: 202px;
		height: auto;
		margin: 0;}

	h3{
		margin: 0 0 8px 0;
		padding: 0;
	}

	.email_ctn{
		padding: 8px 25px 14px 12px;
		background-color: #F1F1F1;
		margin: 30px 0px 32px 0px;
	}

	.title_of_work{
		cursor: pointer;
		font-size: 14px;
	}

	.title_of_work:hover{
		text-decoration: underline;
	}

	.piece_of_work{
		display: none;
	}

	.piece_header{
		padding-top: 8px;
	}

	.go_back_btn{
		cursor: pointer; 
		font-size: 20px;
		padding-top: 10px;
	}

	#get_page_like_this{
		display: none;
	}

	.my_page_footer{
		width: 100%;
		text-align: center;
		height: 40px;
		line-height: 2.8;
		margin-top: 40px;
		background: #F1F1F1;		
	}
</style>


<script type="text/javascript">
	function show_piece(piece_id){
		// hide main
		default_page_body = document.getElementById("default_page_body");
		default_page_body.style.display = "none";
		// display piece
		piece_of_writing = document.getElementById(piece_id);
		piece_of_writing.style.display = "block";	
	}

	function show_default(piece_id){
		// hide current piece
		piece_of_writing = document.getElementById(piece_id);
		piece_of_writing.style.display = "none";

		// show main
		default_page_body = document.getElementById("default_page_body");
		default_page_body.style.display = "block";
	}

	function show_get_page(){
		// hide main
		default_page_body = document.getElementById("default_page_body");
		default_page_body.style.display = "none";
		default_page_body = document.getElementById("piece_zero");
		default_page_body.style.display = "none";
		default_page_body = document.getElementById("piece_one");
		default_page_body.style.display = "none";
		default_page_body = document.getElementById("piece_two");
		default_page_body.style.display = "none";
		default_page_body = document.getElementById("piece_three");
		default_page_body.style.display = "none";
		default_page_body = document.getElementById("piece_four");
		default_page_body.style.display = "none";
		default_page_body = document.getElementById("piece_five");
		default_page_body.style.display = "none";
		default_page_body = document.getElementById("piece_six");
		default_page_body.style.display = "none";
		default_page_body = document.getElementById("piece_seven");
		default_page_body.style.display = "none";
		piece_of_writing = document.getElementById("get_page_like_this");
		piece_of_writing.style.display = "block";		
	}
</script>